# use a Mac OSX image
# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# run the script to download and install Unity editor using Homebrew's python (openssl)
install:
  - brew update
  - brew upgrade openssl
  - brew link --force openssl
  - sudo /usr/local/bin/python2 scripts/install-unity.py 2017.2

# run the script for unit tests and builds
jobs:
  include:
    - stage: integration
      language: generic
      script: sh scripts/integration.sh
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - stage: unit
      script: sh scripts/test.sh
      language: generic
      os: osx
